In [ ]:
# (주)이수앱지스	086890 2012/12  100
df.loc[(df['거래소코드'] == '086890') & (df['회계년도']=='2012/12'), '종업원수'] = 100

# 갤럭시아머니트리(주)	094480	2012/12  100
df.loc[(df['거래소코드'] == '094480') & (df['회계년도']=='2012/12'), '종업원수'] = 100

# (주)에스에이엠티	031330	2012/12	 100
df.loc[(df['거래소코드'] == '031330') & (df['회계년도']=='2012/12'), '종업원수'] = 100

# 파미셀(주)	005690 2012/12  100
df.loc[(df['거래소코드'] == '005690') & (df['회계년도']=='2012/12'), '종업원수'] = 100

###### dart 해당년도 사업보고서에 직원수 나오지 않음
# 2012.9 분기보고서 종업원수 239
# 2013.3 분기보고서 종업원수 274
# 239+274 = 256.5 = 257 (올림)   사업보고서가 12.31기준 종업원수를 작성하므로 사업보고서 앞뒤 분기보고서의 평균값을 올림하여 사용
# (주)루멘스	038060	2012/12    (dart)
df.loc[(df['거래소코드'] == '038060') & (df['회계년도']=='2012/12'), '종업원수'] = 257

# (주)썬테크놀로지스	122800 2012/12    (dart)
# 2012.12 앞뒤 분기보고서에 종업원수 없음
# 전년도 종업원수 없음
# 2013. 2분기, 3분기보고서에도 종업원수 없음
# 2013년 종업원수 사용 95
df.loc[(df['거래소코드'] == '122800') & (df['회계년도']=='2012/12'), '종업원수'] = 95


# 2013
# 세미텍(주)	081220	2013/12	   dart  기타법인, 종업원수 안나옴, 기타법인, 201312 감사보고서 1개 나옴
# 13년 9월 30일 기준  종업원수 344  (2013.11.27) 정정신고 보고서 사용
df.loc[(df['거래소코드'] == '081220') & (df['회계년도']=='2013/12'), '종업원수'] = 344

# (주)씨유전자	056340	2013/12	  dart  2014.5.8 부도발생   
# 2013.12 보고서에 종업원수 없음
# 2013.9 보고서에 나온 종업원수 14 사용
df.loc[(df['거래소코드'] == '056340') & (df['회계년도']=='2013/12'), '종업원수'] = 14

# (주)에스에프씨	112240	2013/12	100
df.loc[(df['거래소코드'] == '112240') & (df['회계년도']=='2013/12'), '종업원수'] = 100

# 키네마스터(주)	139670	2013/12
df.loc[(df['거래소코드'] == '139670') & (df['회계년도']=='2013/12'), '종업원수'] = 100

# 나노캠텍(주)	091970	2013/12	100
df.loc[(df['거래소코드'] == '091970') & (df['회계년도']=='2013/12'), '종업원수'] = 100

# (주)슈프리마에이치큐	094840	2013/12 100
df.loc[(df['거래소코드'] == '094840') & (df['회계년도']=='2013/12'), '종업원수'] = 100

# (주)ES큐브	050120	2013/12	100
df.loc[(df['거래소코드'] == '050120') & (df['회계년도']=='2013/12'), '종업원수'] = 100

# (주)위메이드맥스	101730	2013/12	
df.loc[(df['거래소코드'] == '101730') & (df['회계년도']=='2013/12'), '종업원수'] = 100


#2014
#일진전기(주)	103590	2014/12  1000
df.loc[(df['거래소코드'] == '103590') & (df['회계년도']=='2014/12'), '종업원수'] = 1000

# (주)앤씨앤	092600	2014/12	  100
df.loc[(df['거래소코드'] == '092600') & (df['회계년도']=='2014/12'), '종업원수'] = 100

# (주)슈피겐코리아	192440	2014/12	100
df.loc[(df['거래소코드'] == '192440') & (df['회계년도']=='2014/12'), '종업원수'] = 100

# (주)이지	037370	2014/12   100
df.loc[(df['거래소코드'] == '037370') & (df['회계년도']=='2014/12'), '종업원수'] = 100

##### (주)스페코 2014/12  013810  종업원수 96 
df.loc[(df['거래소코드'] == '013810') & (df['회계년도']=='2014/12'), '종업원수'] = 96

# 조광아이엘아이(주)	044060	2014/12	  100
df.loc[(df['거래소코드'] == '044060') & (df['회계년도']=='2014/12'), '종업원수'] = 100


# 2015
# 한화화인케미칼(주)	025850	2015/12	0.0000    # 한화케미칼로 흡수 합병됨 2015.12.11
# 2015 사업보고서 미존재
# 2015.9 반기보고서 - 종업원수 129
df.loc[(df['거래소코드'] == '025850') & (df['회계년도']=='2015/12'), '종업원수'] = 129 

#(주)케이사인	192250	2015/12	100
df.loc[(df['거래소코드'] == '192250') & (df['회계년도']=='2015/12'), '종업원수'] = 100

#파나케이아(주)	058530	2015/12	 100
df.loc[(df['거래소코드'] == '058530') & (df['회계년도']=='2015/12'), '종업원수'] = 100

##### (주)네이처셀  2015/12 종업원수 100
df.loc[(df['거래소코드'] == '007390') & (df['회계년도']=='2015/12'), '종업원수'] = 100

# (주)동아엘텍	088130	2015/12 100
df.loc[(df['거래소코드'] == '088130') & (df['회계년도']=='2015/12'), '종업원수'] = 100

# (주)흥국  010240  2015/12 100
df.loc[(df['거래소코드'] == '010240') & (df['회계년도']=='2015/12'), '종업원수'] = 100

# (주)새로닉스	042600	2015/12  1000 다트  
df.loc[(df['거래소코드'] == '042600') & (df['회계년도']=='2015/12'), '종업원수'] = 1000

# 삼지전자(주)	037460	2015/12  100
df.loc[(df['거래소코드'] == '037460') & (df['회계년도']=='2015/12'), '종업원수'] = 100
        
# (주)서희건설	035890	2015/12    1000
df.loc[(df['거래소코드'] == '035890') & (df['회계년도']=='2015/12'), '종업원수'] = 1000

# (주)코메론	049430	2015/12 100
df.loc[(df['거래소코드'] == '049430') & (df['회계년도']=='2015/12'), '종업원수'] = 100


# 2016
#(주)코이즈	121850	2016/12	100
df.loc[(df['거래소코드'] == '121850') & (df['회계년도']=='2016/12'), '종업원수'] = 100
#(주)셀피글로벌	068940	2016/12	100
df.loc[(df['거래소코드'] == '068940') & (df['회계년도']=='2016/12'), '종업원수'] = 100
#(주)웹스	196700	2016/12	100
df.loc[(df['거래소코드'] == '196700') & (df['회계년도']=='2016/12'), '종업원수'] = 100
#(주)엔케이맥스	182400	2016/12	100
df.loc[(df['거래소코드'] == '182400') & (df['회계년도']=='2016/12'), '종업원수'] = 100


# 2017
#(주)동방선기	099410	2017/12  116
df.loc[(df['거래소코드'] == '099410') & (df['회계년도']=='2017/12'), '종업원수'] = 116
#(주)에이루트	096690	2017/12   150
df.loc[(df['거래소코드'] == '096690') & (df['회계년도']=='2017/12'), '종업원수'] = 150
#한국화장품(주)	123690	2017/12  100
df.loc[(df['거래소코드'] == '123690') & (df['회계년도']=='2017/12'), '종업원수'] = 100

##### 중앙에너비스 2017/12 종업원수 100
df.loc[(df['거래소코드'] == '000440') & (df['회계년도']=='2017/12'), '종업원수'] = 100 
# (주)코오롱	002020	2017/12  100
df.loc[(df['거래소코드'] == '002020') & (df['회계년도']=='2017/12'), '종업원수'] = 100

# (주)제이테크놀로지	035480  2017/12   ts2000 - 2019.12.12 상장폐지 
# 다트에서 "제이테크놀로지" 검색하면 2017 감사보고서 나오지만 종업원수 찾지 못함
# 다트 035480(거래소코드) 검색 시    글로앤웰 이라는 기업이 나옴 (사명변경)
# 기업명 : 글로앤웰 기타법인  109명 #
df.loc[(df['거래소코드'] == '035480') & (df['회계년도']=='2017/12'), '종업원수'] = 109


# 2018
# (주)쎄노텍	222420	2018/12   100
df.loc[(df['거래소코드'] == '222420') & (df['회계년도']=='2018/12'), '종업원수'] = 100 

#### (주)에이프로젠바이오로직스	003060	2018/12	 100
df.loc[(df['거래소코드'] == '003060') & (df['회계년도']=='2018/12'), '종업원수'] = 100 

#### (주)아이엠비씨	052220	2018/12	 100
df.loc[(df['거래소코드'] == '052220') & (df['회계년도']=='2018/12'), '종업원수'] = 100 

# 옵티시스(주)	109080	2018/12	100
df.loc[(df['거래소코드'] == '109080') & (df['회계년도']=='2018/12'), '종업원수'] = 100 

# (주)코디	080530	2018/12  100
df.loc[(df['거래소코드'] == '080530') & (df['회계년도']=='2018/12'), '종업원수'] = 100 


# 2019
# 이엘케이(주)	094190	2019/12	100
df.loc[(df['거래소코드'] == '094190') & (df['회계년도']=='2019/12'), '종업원수'] = 100

# 에스엘(주)	005850	2019/12  4107
df.loc[(df['거래소코드'] == '005850') & (df['회계년도']=='2019/12'), '종업원수'] = 4107

# (주)제넨바이오	072520	2019/12  100
df.loc[(df['거래소코드'] == '072520') & (df['회계년도']=='2019/12'), '종업원수'] = 100

# (주)주연테크	044380	2019/12 100
df.loc[(df['거래소코드'] == '044380') & (df['회계년도']=='2019/12'), '종업원수'] = 100

# (주)이수페타시스	007660	2019/12	903
df.loc[(df['거래소코드'] == '007660') & (df['회계년도']=='2019/12'), '종업원수'] = 903

# (주)세토피아	222810	2019/12	 45
df.loc[(df['거래소코드'] == '222810') & (df['회계년도']=='2019/12'), '종업원수'] = 45

# (주)화진	134780	2019/12   240
df.loc[(df['거래소코드'] == '134780') & (df['회계년도']=='2019/12'), '종업원수'] = 240

# 삼보모터스(주)	053700 2019/12 479
df.loc[(df['거래소코드'] == '053700') & (df['회계년도']=='2019/12'), '종업원수'] = 479
        
# (주)이엠앤아이	083470	2019/12  16
df.loc[(df['거래소코드'] == '083470') & (df['회계년도']=='2019/12'), '종업원수'] = 16

# 경창산업(주)	024910	2019/12   88
df.loc[(df['거래소코드'] == '024910') & (df['회계년도']=='2019/12'), '종업원수'] = 88


# 2020
# (주)아톤	158430	2020/12	100
df.loc[(df['거래소코드'] == '158430') & (df['회계년도']=='2020/12'), '종업원수'] = 100 

#효성첨단소재(주)	298050	2020/12	1000
df.loc[(df['거래소코드'] == '298050') & (df['회계년도']=='2020/12'), '종업원수'] = 1000

# (주)씨엔플러스	115530	2020/12  34
df.loc[(df['거래소코드'] == '115530') & (df['회계년도']=='2020/12'), '종업원수'] = 34

# (주)노블엠앤비	106520	2020/12  100
df.loc[(df['거래소코드'] == '106520') & (df['회계년도']=='2020/12'), '종업원수'] = 100 

# (주)소리바다	053110	2020/12  67
df.loc[(df['거래소코드'] == '053110') & (df['회계년도']=='2020/12'), '종업원수'] = 67 

# (주)연이비앤티	090740	2020/12 	38
df.loc[(df['거래소코드'] == '090740') & (df['회계년도']=='2020/12'), '종업원수'] = 38

# (주)원익	032940	2020/12	 100
df.loc[(df['거래소코드'] == '032940') & (df['회계년도']=='2020/12'), '종업원수'] = 100 


# 2021
# (주)보광산업	225530	2021/12  100
df.loc[(df['거래소코드'] == '225530') & (df['회계년도']=='2021/12'), '종업원수'] = 100 

# (주)그리티	204020	2021/12	  100
df.loc[(df['거래소코드'] == '204020') & (df['회계년도']=='2021/12'), '종업원수'] = 100

#(주)오하임앤컴퍼니	309930	2021/12	100
df.loc[(df['거래소코드'] == '309930') & (df['회계년도']=='2021/12'), '종업원수'] = 100 

# (주)한일진공	123840	2021/12	 
df.loc[(df['거래소코드'] == '123840') & (df['회계년도']=='2021/12'), '종업원수'] = 100 

# 오비고 352910  2021/12 100
df.loc[(df['거래소코드'] == '352910') & (df['회계년도']=='2021/12'), '종업원수'] = 100 

# 경남스틸(주)	039240	2021/12  100
df.loc[(df['거래소코드'] == '039240') & (df['회계년도']=='2021/12'), '종업원수'] = 100 

# 	(주)동국에스엔씨	100130	2021/12  100
df.loc[(df['거래소코드'] == '100130') & (df['회계년도']=='2021/12'), '종업원수'] = 100
        
# 에스디엔(주)	099220	2021/12   100
df.loc[(df['거래소코드'] == '099220') & (df['회계년도']=='2021/12'), '종업원수'] = 100

# 영풍제지(주)	006740	2021/12  100
df.loc[(df['거래소코드'] == '006740') & (df['회계년도']=='2021/12'), '종업원수'] = 100


## 000830   삼성물산
df.loc[(df['거래소코드'] == '000830') & (df['회계년도']=='2012/12'), '종업원수'] = 7860
df.loc[(df['거래소코드'] == '000830') & (df['회계년도']=='2013/12'), '종업원수'] = 8714


## 동신건설(주)	025950	2012/12	100
## 동신건설(주)	025950	2016/12	100
df.loc[(df['거래소코드'] == '025950') & (df['회계년도']=='2012/12'), '종업원수'] = 100
df.loc[(df['거래소코드'] == '025950') & (df['회계년도']=='2016/12'), '종업원수'] = 100

## 경남스틸(주)	039240	2021/12	100
## 경남스틸(주)	039240	2022/12	100
df.loc[(df['거래소코드'] == '039240') & (df['회계년도']=='2021/12'), '종업원수'] = 100
df.loc[(df['거래소코드'] == '039240') & (df['회계년도']=='2022/12'), '종업원수'] = 100

## (주)이엠네트웍스	087730	2016/12	100
## (주)이엠네트웍스	087730	2020/12	90
df.loc[(df['거래소코드'] == '087730') & (df['회계년도']=='2016/12'), '종업원수'] = 100
df.loc[(df['거래소코드'] == '087730') & (df['회계년도']=='2020/12'), '종업원수'] = 90

## (주)비지에프에코머티리얼즈	126600	2016/12 100
## (주)비지에프에코머티리얼즈	126600	2019/12	100
df.loc[(df['거래소코드'] == '126600') & (df['회계년도']=='2016/12'), '종업원수'] = 100
df.loc[(df['거래소코드'] == '126600') & (df['회계년도']=='2019/12'), '종업원수'] = 100

## (주)엑세스바이오인코퍼레이션	950130	2015/12	   68 (dart)
## (주)엑세스바이오인코퍼레이션	950130	2016/12	  65
df.loc[(df['거래소코드'] == '950130') & (df['회계년도']=='2015/12'), '종업원수'] = 68
df.loc[(df['거래소코드'] == '950130') & (df['회계년도']=='2016/12'), '종업원수'] = 65

## 잉글우드랩(주)	950140	2016/12	168
## 잉글우드랩(주)	950140	2017/12     365 (dart)
df.loc[(df['거래소코드'] == '950140') & (df['회계년도']=='2016/12'), '종업원수'] = 168
df.loc[(df['거래소코드'] == '950140') & (df['회계년도']=='2017/12'), '종업원수'] = 365


# 애머릿지코퍼레이션	900100   12년~17년 채우기
df.loc[(df['거래소코드'] == '900100') & (df['회계년도']=='2012/12'), '종업원수'] = 176
df.loc[(df['거래소코드'] == '900100') & (df['회계년도']=='2013/12'), '종업원수'] = 128
df.loc[(df['거래소코드'] == '900100') & (df['회계년도']=='2014/12'), '종업원수'] = 154
df.loc[(df['거래소코드'] == '900100') & (df['회계년도']=='2015/12'), '종업원수'] = 151
df.loc[(df['거래소코드'] == '900100') & (df['회계년도']=='2016/12'), '종업원수'] = 168
df.loc[(df['거래소코드'] == '900100') & (df['회계년도']=='2017/12'), '종업원수'] = 105

# 애머릿지코퍼레이션	900100	2019/12   398  
# 애머릿지코퍼레이션	900100	2020/12   11
df.loc[(df['거래소코드'] == '900100') & (df['회계년도']=='2019/12'), '종업원수'] = 398
df.loc[(df['거래소코드'] == '900100') & (df['회계년도']=='2020/12'), '종업원수'] = 11